sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install tox tox-travis coverage coveralls

script:
  - tox

after_success:
  - coverage report --omit="aa_intercom/tests/*" -m
  - coveralls

notifications:
  email:
    recipients:
      - team@arabel.la
